seleniumhub:
  image: selenium/hub:2.53.1
  ports:
    - 4444:4444
  environment:
    - no_proxy=localhost

firefoxnode:
  image: selenium/node-firefox-debug:2.53.1
  ports:
    - 5900
  environment:
    - no_proxy=localhost
  links:
    - seleniumhub:hub

chromenode:
  image: selenium/node-chrome-debug:2.53.1
  ports:
    - 5901
  environment:
    - no_proxy=localhost
  links:
    - seleniumhub:hub

#Running tests on standalone chrome or firefox

#selenium:
#  image: selenium/standalone-chrome-debug:2.53.1
#  ports:
#    - 4444:4444
#  environment:
#    - no_proxy=localhost
#
#selenium:
#  image: selenium/standalone-firefox-debug:2.53.1
#  ports:
#    - 5901:5901
#  environment:
#    - no_proxy=localhost

#seleniumtest:
#  image: abnair/dockermvn
#  ports:
#    - 5001:5001
#  links:
#    - seleniumhub:localhost
#  container_name: mvntests
#  command: bash -c "git clone https://github.com/mirroredthoughts/Dockertests.git && cd Dockertests && mvn clean test && tail -f /dev/null"
